version: "2.2"

services:
  # Web
  webhooks:
    restart: always
    env_file:
    - ./.env
    networks:
      - web
      - internal
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.frontend.rule: "Host: fb.example.com; PathPrefix: /webhooks.php"
      traefik.frontend.headers.customResponseHeaders: "X-Robots-Tag: noindex, nofollow, noarchive"
      traefik.port: "80"
    build: ../

  ui:
    restart: always
    env_file:
    - ./.env
    networks:
      - web
      - internal
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.frontend.rule: "Host: fb.example.com"
      traefik.frontend.headers.customResponseHeaders: "X-Robots-Tag: noindex, nofollow, noarchive"
      # todo: traefik.frontend.auth.basic: "..."
      traefik.port: "80"
    build: ../

  # DB
  db:
    restart: always
    networks:
      - internal
    image: postgres:12-alpine
    volumes:
      - ../Database/combinaryFacebook.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    environment:
      - POSTGRES_DB=${DB_NAME:-combinaryfbook}
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PWD:-user}

networks:
  internal:
  web:
    external: true