version: "2.2"

services:
  # Web
  web:
    hostname: web
    image: ${WEB_IMAGE:-docksal/web:2.1-apache2.4}
    volumes:
      - ../:/var/www:ro  # Project root volume (read-only)
    environment:
      - APACHE_DOCUMENTROOT=/var/www/${DOCROOT:-docroot}
      - APACHE_BASIC_AUTH_USER
      - APACHE_BASIC_AUTH_PASS

  # DB: PostgreSQL
  pgsql:
    hostname: db
    image: ${DB_IMAGE:-postgres:12-alpine}
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-combinaryfbook}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1234}

  # CLI - Used for all console commands and tools.
  cli:
    hostname: cli
    image: ${CLI_IMAGE:-docksal/cli:2.2-php7.1}
    volumes:
      - ../:/var/www:rw  # Project root volume
      - /home/docker  # Write-heavy directories should be in volumes. See https://github.com/docksal/docksal/issues/325
    environment:
      - HOST_UID
      - HOST_GID
      - DOCROOT
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN
      - SECRET_SSH_PRIVATE_KEY
      - SECRET_ACAPI_EMAIL
      - SECRET_ACAPI_KEY
      - SECRET_TERMINUS_TOKEN
